# Generated by Django 6.0.2 on 2026-02-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_images/"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
